apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.orpheusdroid.sqliteviewer"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0-RC1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    signingConfigs {
        release
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    flavorDimensions "tier"
    productFlavors {
        playstore {
            dimension "tier"
            buildConfigField "String", "APP_PUB_KEY", getAppKey("app_pub_key")
        }
        fdroid {
            dimension "tier"
        }
    }
}

static def getAppKey(String property){
    Properties properties = new Properties()
    properties.load(new FileInputStream("app_pub_key"))
    return "\"" + properties.getProperty(property) +"\""
}

if (project.hasProperty('RELEASE_STORE_FILE')) {
    println 'Using release keys'
    android.signingConfigs.release.storeFile new File(RELEASE_STORE_FILE)
    android.signingConfigs.release.storePassword RELEASE_STORE_PASSWORD
    android.signingConfigs.release.keyAlias RELEASE_KEY_ALIAS
    android.signingConfigs.release.keyPassword RELEASE_KEY_PASSWORD
} else {
    println 'Release keys not found. Falling back to default config'
    android.buildTypes.release.signingConfig = null
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.github.topjohnwu:libsu:2.0.0'
    implementation 'com.evrencoskun.library:tableview:0.8.8'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation('com.github.ViksaaSkool:AwesomeSplash:v1.0.0', {
        exclude group: 'com.android.support'
    })
    implementation 'com.android.support:cardview-v7:27.1.1'

    implementation 'de.siegmar:fastcsv:1.0.2'

    fdroidImplementation 'ly.count.android:sdk:18.04'

    playstoreImplementation 'ly.count.android:sdk-messaging-fcm:18.04'
    playstoreImplementation 'org.solovyev.android:checkout:1.2.1'
    playstoreImplementation 'com.google.firebase:firebase-messaging:17.1.0'

    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

if (!getGradle().getStartParameter().getTaskRequests()
        .toString().contains("playstore")){
    apply plugin: 'com.google.gms.google-services'
}
